language: cpp
compiler: clang
os: linux
dist: trusty

addons:
  apt:
    packages:
      - pkg-config
      - glibmm-2.4
      - libssl-dev
      - libcurl4-openssl-dev
      - software-properties-common
      - build-essential
      - python-dev
      - autotools-dev
      - libicu-dev
      - build-essential
      - libbz2-dev

before_script:
  - curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y \
      clang-6.0 \
      gcc-6 \
      g++-6

install:
  # Set the ${CXX} variable properly
  - export CXX=clang++-6.0
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.12.0
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

script:
  - cmake --build . -- -j${JOBS}
  - ./bin/flash-test
