version: 2

jobs:
  linux:
    docker:
      - image: tinganho/dev.env.flashpoint:latest

    steps:
      - checkout

      - run:
          name: Clone submodules
          command: git submodule update --init --recursive

      - run:
          name: CMake Install
          command: |
            cmake --version
            mkdir debug
            cd debug
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang ..
            make
      - run:
          name: Test
          command: ./bin/flash-test
  mac:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    steps:
      - checkout
      - run:
          name: Install
          command: |
            brew install cmake boost pkg-config
      - run:
          name: Build
          command: |
            cmake --version
            mkdir debug
            cd debug
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang ..
            make
      - run:
          name: Test
          command: ./bin/flash-test

workflows:
  version: 2
  linux:
    jobs:
      - linux
  mac:
    jobs:
      - mac